# Generated by Django 4.2.29 on 2026-03-16 11:08

import Owners.Folders
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Owners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleRental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle', models.CharField(choices=[('bike', 'Bike'), ('sedan', 'Sedan'), ('suv', 'SUV'), ('mini', 'Mini Car'), ('hatchback', 'Hatchback'), ('luxury', 'Luxury Car')], max_length=70)),
                ('registration_number', models.CharField(max_length=70, unique=True)),
                ('vehiclemodel', models.CharField(max_length=70)),
                ('brand', models.CharField(max_length=70)),
                ('year', models.CharField(max_length=70)),
                ('colour', models.CharField(max_length=70)),
                ('seat_capacity', models.PositiveIntegerField(default=4)),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('cng', 'CNG'), ('electric', 'Electric')], default='petrol', max_length=20)),
                ('transmission_type', models.CharField(choices=[('manual', 'MANUAL'), ('automatic', 'AUTOMATIC')], max_length=100)),
                ('rc_book_image', models.ImageField(blank=True, null=True, upload_to=Owners.Folders.rc_book_upload_path)),
                ('insurance_image', models.ImageField(blank=True, null=True, upload_to=Owners.Folders.insurance_upload_path)),
                ('insurance_expiary', models.ImageField(blank=True, null=True, upload_to=Owners.Folders.insurance_upload_path)),
                ('pollution_image', models.ImageField(blank=True, null=True, upload_to=Owners.Folders.pollution_upload_path)),
                ('pollution_expiary', models.ImageField(blank=True, null=True, upload_to=Owners.Folders.pollution_upload_path)),
                ('vehicle_front', models.ImageField(blank=True, null=True, upload_to=Owners.Folders.vehicle_photo_upload_path)),
                ('vehicle_right', models.ImageField(blank=True, null=True, upload_to=Owners.Folders.vehicle_photo_upload_path)),
                ('Vehicle_left', models.ImageField(blank=True, null=True, upload_to=Owners.Folders.vehicle_photo_upload_path)),
                ('vehicle_back', models.ImageField(blank=True, null=True, upload_to=Owners.Folders.vehicle_photo_upload_path)),
                ('vehicle_seats_front', models.ImageField(blank=True, null=True, upload_to=Owners.Folders.vehicle_photo_upload_path)),
                ('vehicle_trumpat', models.ImageField(blank=True, null=True, upload_to=Owners.Folders.vehicle_photo_upload_path)),
                ('vehicle_Seats_back', models.ImageField(blank=True, null=True, upload_to=Owners.Folders.vehicle_photo_upload_path)),
                ('is_active', models.CharField(choices=[('available', 'Available'), ('rented', 'Currently Rented'), ('maintenance', 'Under Maintenance'), ('inactive', 'Inactive')], default='avaliable', max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('rental_price_per_hour', models.DecimalField(blank=True, decimal_places=2, help_text='Hourly rental price', max_digits=10, null=True)),
                ('rental_price_per_day', models.DecimalField(blank=True, decimal_places=2, help_text='day rental price', max_digits=10, null=True)),
                ('security_depoist', models.DecimalField(blank=True, decimal_places=2, help_text='Security Depoist', max_digits=10, null=True)),
                ('min_rental_hours', models.IntegerField(default=6, help_text='Minimum rental duration in hours')),
                ('max_rental_days', models.IntegerField(default=30, help_text='Maximum rental duration in days')),
                ('km_limit_per_day', models.IntegerField(default=200, help_text='KM limit per day')),
                ('extra_km_charge', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('has_ac', models.BooleanField(default=True)),
                ('has_music_system', models.BooleanField(default=True)),
                ('has_gps', models.BooleanField(default=False)),
                ('has_bluetooth', models.BooleanField(default=True)),
                ('total_rentals', models.IntegerField(default=0)),
                ('total_distance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('current_km', models.IntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(help_text='Vehicle owner', on_delete=django.db.models.deletion.CASCADE, related_name='rental_vehicles', to='Owners.vehicleownerprofile')),
            ],
            options={
                'verbose_name': 'Rental Vehicle',
                'verbose_name_plural': 'Rental Vehicles',
            },
        ),
        migrations.RemoveField(
            model_name='rentalvehicle',
            name='owner',
        ),
        migrations.DeleteModel(
            name='CustomerVehicleRental',
        ),
        migrations.DeleteModel(
            name='RentalVehicle',
        ),
        migrations.AddIndex(
            model_name='vehiclerental',
            index=models.Index(fields=['is_active', 'is_verified'], name='Owners_vehi_is_acti_000345_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclerental',
            index=models.Index(fields=['vehicle'], name='Owners_vehi_vehicle_1d3ed5_idx'),
        ),
    ]
