# Generated by Django 4.2.29 on 2026-05-05 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Owners', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicleownerprofile',
            old_name='full_name',
            new_name='full_names',
        ),
    ]
