# Generated by Django 4.2.29 on 2026-03-17 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0001_initial'),
        ('Owners', '0002_vehiclerental_remove_rentalvehicle_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclerental',
            name='is_active',
            field=models.CharField(choices=[('available', 'Available'), ('rented', 'Currently Rented'), ('maintenance', 'Under Maintenance'), ('unavaliable', 'Unavaliable')], default='available', max_length=100),
        ),
        migrations.CreateModel(
            name='VehicleRentalBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_type', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily')], default='daily', max_length=10)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('security_deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('security_deposit_paid', models.BooleanField(default=False)),
                ('pickup_otp', models.CharField(blank=True, max_length=6, null=True)),
                ('return_otp', models.CharField(blank=True, max_length=6, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Confirmation'), ('confirmed', 'Confirmed'), ('active', 'Active - Vehicle Picked Up'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('deposit_paid', 'Deposit Paid'), ('full_paid', 'Full Payment Done'), ('refund_pending', 'Refund Pending'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('customer_notes', models.TextField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_bookings', to='Customer.customerprofile')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='Owners.vehiclerental')),
            ],
            options={
                'verbose_name': 'Vehicle Rental Booking',
                'verbose_name_plural': 'Vehicle Rental Bookings',
                'ordering': ['-created_at'],
            },
        ),
    ]
