# Generated by Django 4.2.29 on 2026-05-05 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Owners', '0002_rename_full_name_vehicleownerprofile_full_names'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicleownerprofile',
            old_name='full_names',
            new_name='full_name',
        ),
    ]
