# Generated by Django 4.2.29 on 2026-03-17 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Owners', '0003_alter_vehiclerental_is_active_vehiclerentalbooking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VehicleRentalBooking',
        ),
    ]
