# Generated by Django 4.2.29 on 2026-05-05 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Owners', '0003_rename_full_names_vehicleownerprofile_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleownerprofile',
            name='aadhar_image',
            field=models.ImageField(blank=True, null=True, upload_to='owners/aadhar/'),
        ),
        migrations.AddField(
            model_name='vehicleownerprofile',
            name='pan_image',
            field=models.ImageField(blank=True, null=True, upload_to='owners/pancard/'),
        ),
    ]
