# Generated by Django 4.2.29 on 2026-05-06 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Owners', '0004_vehicleownerprofile_aadhar_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclerental',
            name='vehicle',
            field=models.CharField(choices=[('bike', 'Bike'), ('sedan', 'Sedan'), ('suv', 'SUV'), ('mini', 'Mini Car'), ('hatchback', 'Hatchback'), ('luxury', 'Luxury Car'), ('scooty', 'Scooty')], max_length=70),
        ),
    ]
