# Generated by Django 4.2.29 on 2026-05-06 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Owners', '0005_alter_vehiclerental_vehicle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiclerental',
            old_name='vehicle_Seats_back',
            new_name='vehicle_seats_back',
        ),
    ]
