# Generated by Django 4.2.29 on 2026-05-06 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Owners', '0006_rename_vehicle_seats_back_vehiclerental_vehicle_seats_back'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiclerental',
            old_name='vehicle_seats_back',
            new_name='vehicle_Seats_back',
        ),
    ]
