# Generated by Django 4.2.29 on 2026-05-06 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Owners', '0007_rename_vehicle_seats_back_vehiclerental_vehicle_seats_back'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiclerental',
            old_name='Vehicle_left',
            new_name='vehicle_left',
        ),
    ]
