# Generated by Django 4.2.29 on 2026-05-07 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Owners', '0008_rename_vehicle_left_vehiclerental_vehicle_left'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleownerprofile',
            name='full_name',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
