[project]
name = "driveprotal"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "celery>=5.3.6",
    "channels>=4.0.0",
    "channels-redis>=4.1.0",
    "daphne>=4.0.0",
    "django>=4.2,<5.0",
    "django-cors-headers>=4.3.1",
    "django-environ>=0.11.2",
    "django-rest-framework-gis",
    "djangorestframework>=3.14.0",
    "djangorestframework-gis",
    "djangorestframework-simplejwt>=5.3.1",
    "drf-yasg>=1.21.7",
    "gunicorn>=21.2.0",
    "langchain>=0.1.13",
    "langchain-openai>=0.1.1",
    "langgraph>=0.0.30",
    "mysqlclient>=2.2.8",
    "pillow>=10.2.0",
    "psycopg2-binary>=2.9.9",
    "python-environ>=0.4.54",
    "pytz>=2024.1",
    "redis>=5.0.1",
    "scikit-learn>=1.4.1.post1",
]
