# Generated by Django 4.2.29 on 2026-03-16 06:08

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('license_expiry', models.DateField(blank=True, null=True)),
                ('license_image', models.ImageField(blank=True, null=True, upload_to='drivers/licenses/')),
                ('verification_status', models.CharField(choices=[('pending', 'Pending Verification'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='pending', max_length=20)),
                ('aadhar_number', models.CharField(blank=True, max_length=12, null=True)),
                ('aadhar_image', models.ImageField(blank=True, null=True, upload_to='drivers/aadhar/')),
                ('pan_number', models.CharField(blank=True, max_length=10, null=True)),
                ('pan_image', models.ImageField(blank=True, null=True, upload_to='drivers/pan/')),
                ('is_available', models.BooleanField(default=False)),
                ('is_online', models.BooleanField(default=False)),
                ('current_location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, help_text='Current location of the driver', null=True, srid=4326)),
                ('total_rides_completed', models.IntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('bank_account_number', models.CharField(blank=True, max_length=20, null=True)),
                ('bank_ifsc', models.CharField(blank=True, max_length=11, null=True)),
                ('bank_account_holder_name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Driver Profile',
                'verbose_name_plural': 'Driver Profiles',
            },
        ),
        migrations.CreateModel(
            name='DriverVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('auto', 'Auto Rickshaw'), ('bike', 'Bike'), ('sedan', 'Sedan'), ('suv', 'SUV'), ('mini', 'Mini Car'), ('hatchback', 'Hatchback')], max_length=20)),
                ('registration_number', models.CharField(max_length=20, unique=True)),
                ('model', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('color', models.CharField(max_length=50)),
                ('seating_capacity', models.IntegerField(default=4)),
                ('rc_book_image', models.ImageField(blank=True, null=True, upload_to='driver_vehicles/rc_books/')),
                ('insurance_image', models.ImageField(blank=True, null=True, upload_to='driver_vehicles/insurance/')),
                ('insurance_expiry', models.DateField(blank=True, null=True)),
                ('pollution_certificate', models.ImageField(blank=True, null=True, upload_to='driver_vehicles/pollution/')),
                ('pollution_expiry', models.DateField(blank=True, null=True)),
                ('vehicle_image', models.ImageField(blank=True, null=True, upload_to='driver_vehicles/photos/')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Under Maintenance')], default='active', max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_primary', models.BooleanField(default=True, help_text="Is this the driver's primary vehicle for rides?")),
                ('total_rides', models.IntegerField(default=0)),
                ('total_distance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('current_km', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(help_text='Driver who owns this vehicle', on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='Driver.driverprofile')),
            ],
            options={
                'verbose_name': 'Driver Vehicle',
                'verbose_name_plural': 'Driver Vehicles',
            },
        ),
        migrations.AddIndex(
            model_name='driverprofile',
            index=models.Index(fields=['is_available', 'is_online', 'verification_status'], name='Driver_driv_is_avai_d40622_idx'),
        ),
    ]
