# Generated by Django 4.2.29 on 2026-03-16 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Driver', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DriverVehicle',
        ),
    ]
