# Generated by Django 4.2.29 on 2026-03-17 06:47

import Driver.Folders
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Driver', '0002_delete_drivervehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle', models.CharField(choices=[('bike', 'BIKE'), ('scooty', 'SCOOTY'), ('car', 'CAR'), ('loory', 'LOORY')], max_length=100)),
                ('registration_number', models.CharField(blank=True, max_length=70, unique=True)),
                ('vehiclemodel', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('colour', models.CharField(max_length=100)),
                ('seat_capacity', models.PositiveIntegerField(default=1)),
                ('rc_book_image', models.ImageField(blank=True, null=True, upload_to=Driver.Folders.rc_book_upload_path)),
                ('insurance_image', models.ImageField(blank=True, null=True, upload_to=Driver.Folders.insurance_upload_path)),
                ('insurance_expiary', models.ImageField(blank=True, null=True, upload_to=Driver.Folders.insurance_upload_path)),
                ('pollution_image', models.ImageField(blank=True, null=True, upload_to=Driver.Folders.pollution_upload_path)),
                ('pollution_expiary', models.ImageField(blank=True, null=True, upload_to=Driver.Folders.pollution_upload_path)),
                ('vehicle_front', models.ImageField(blank=True, null=True, upload_to=Driver.Folders.vehicle_photo_upload_path)),
                ('is_active', models.CharField(choices=[('avaliable', 'AVALIABLE'), ('not avaliable', 'NOT AVALIABLE'), ('running', 'Running')], default='avaliable', max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('sharing_price', models.DecimalField(blank=True, decimal_places=2, help_text='Hourly rental price', max_digits=10, null=True)),
                ('fully_price', models.DecimalField(blank=True, decimal_places=2, help_text='day rental price', max_digits=10, null=True)),
                ('extra_km_charge', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('has_ac', models.BooleanField(default=True)),
                ('total_rentals', models.IntegerField(default=0)),
                ('total_distance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('current_km', models.IntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(help_text='driver_vehicles', on_delete=django.db.models.deletion.CASCADE, to='Driver.driverprofile')),
            ],
            options={
                'verbose_name': 'Driver Vehicle',
                'verbose_name_plural': 'Driver Vehicles',
                'indexes': [models.Index(fields=['is_active', 'is_verified'], name='Driver_driv_is_acti_03a6d4_idx'), models.Index(fields=['vehicle'], name='Driver_driv_vehicle_4aa004_idx')],
            },
        ),
    ]
