# Generated by Django 4.2.29 on 2026-03-17 11:39

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0001_initial'),
        ('Driver', '0003_drivervehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivervehicle',
            name='ride_type',
            field=models.CharField(choices=[('sharing', 'SHARING'), ('fully', 'FULLY'), ('notmention', 'NOTMENTION')], default='notmention', max_length=100),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='license_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='drivervehicle',
            name='is_active',
            field=models.CharField(choices=[('avaliable', 'AVALIABLE'), ('notavaliable', 'NOTAVALIABLE'), ('running', 'Running')], default='notavaliable', max_length=100),
        ),
        migrations.CreateModel(
            name='SharedRideRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_name', models.CharField(max_length=200)),
                ('destination_name', models.CharField(max_length=200)),
                ('origin_point', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('destination_point', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('departure_time', models.DateTimeField()),
                ('available_seats', models.PositiveIntegerField(default=1)),
                ('price_per_seat', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('started', 'Started'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver_vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_routes', to='Driver.drivervehicle')),
            ],
            options={
                'verbose_name': 'Shared Ride Route',
                'verbose_name_plural': 'Shared Ride Routes',
                'ordering': ['departure_time'],
            },
        ),
        migrations.CreateModel(
            name='SharedRideBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats_booked', models.PositiveIntegerField(default=1)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('booking_status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('pickup_point', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('pickup_address', models.CharField(blank=True, max_length=200, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_bookings', to='Customer.customerprofile')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='Driver.sharedrideroute')),
            ],
            options={
                'verbose_name': 'Shared Ride Booking',
                'verbose_name_plural': 'Shared Ride Bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FullRideRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_point', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('drop_point', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('pickup_address', models.TextField()),
                ('drop_address', models.TextField()),
                ('vehicle_type_requested', models.CharField(choices=[('bike', 'Bike'), ('scooty', 'Scooty'), ('car', 'Car'), ('lorry', 'Lorry')], default='car', max_length=20)),
                ('status', models.CharField(choices=[('searching', 'Searching for Driver'), ('driver_assigned', 'Driver Assigned'), ('started', 'Ride Started'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='searching', max_length=20)),
                ('estimated_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='full_ride_requests', to='Customer.customerprofile')),
            ],
            options={
                'verbose_name': 'Full Ride Request',
                'verbose_name_plural': 'Full Ride Requests',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='FullRideAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='full_ride_assignments', to='Driver.driverprofile')),
                ('driver_vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='full_ride_assignments', to='Driver.drivervehicle')),
                ('ride_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='Driver.fullriderequest')),
            ],
            options={
                'verbose_name': 'Full Ride Assignment',
                'verbose_name_plural': 'Full Ride Assignments',
            },
        ),
        migrations.AddIndex(
            model_name='sharedrideroute',
            index=models.Index(fields=['status', 'departure_time'], name='Driver_shar_status_9a8ba1_idx'),
        ),
    ]
