# Generated by Django 4.2.29 on 2026-04-21 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Driver', '0004_drivervehicle_ride_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='full_name',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
