# Generated by Django 4.2.29 on 2026-04-21 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Driver', '0005_driverprofile_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivervehicle',
            name='driver',
            field=models.ForeignKey(help_text='driver_vehicles', on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='Driver.driverprofile'),
        ),
    ]
