# Generated by Django 4.2.29 on 2026-05-07 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Driver', '0006_alter_drivervehicle_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivervehicle',
            name='vehicle',
            field=models.CharField(choices=[('bike', 'Bike'), ('auto', 'Auto'), ('scooty', 'Scooty'), ('car_mini', 'Car – Mini '), ('car_sedan', 'Car – Sedan '), ('car_suv', 'Car – SUV '), ('car_premium', 'Car - Premium '), ('lorry', 'Lorry')], max_length=100),
        ),
    ]
