# Generated by Django 4.2.29 on 2026-05-11 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Driver', '0007_alter_drivervehicle_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='driver_ride_status',
            field=models.CharField(choices=[('free', 'FREE'), ('onride', 'ONRIDE')], default='free', max_length=20),
        ),
    ]
