# Generated by Django 4.2.29 on 2026-05-11 09:57

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Driver', '0008_driverprofile_driver_ride_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverprofile',
            name='aadhar_number',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.MinLengthValidator(12)]),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='current_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, help_text='Current location of the driver (Longitude, Latitude)', null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='full_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='pan_number',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='drivervehicle',
            name='fully_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='drivervehicle',
            name='is_active',
            field=models.CharField(choices=[('available', 'AVAILABLE'), ('not_available', 'NOT AVAILABLE'), ('running', 'Running')], default='not_available', max_length=100),
        ),
        migrations.AlterField(
            model_name='drivervehicle',
            name='sharing_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
