# Generated by Django 4.2.29 on 2026-05-11 11:12

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Driver', '0009_alter_driverprofile_aadhar_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverprofile',
            name='aadhar_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='current_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, help_text='Current location of the driver', null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='full_name',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='pan_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='drivervehicle',
            name='fully_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='day rental price', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='drivervehicle',
            name='is_active',
            field=models.CharField(choices=[('available', 'AVAILABLE'), ('notavailable', 'NOTAVAILABLE'), ('running', 'Running')], default='notavaliable', max_length=100),
        ),
        migrations.AlterField(
            model_name='drivervehicle',
            name='sharing_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Hourly rental price', max_digits=10, null=True),
        ),
    ]
