# Generated by Django 4.2.29 on 2026-05-12 03:50

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Driver', '0010_alter_driverprofile_aadhar_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverprofile',
            name='current_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='drivervehicle',
            name='is_active',
            field=models.CharField(choices=[('available', 'AVAILABLE'), ('notavailable', 'NOTAVAILABLE'), ('running', 'Running')], default='notavailable', max_length=100),
        ),
    ]
