# Generated by Django 4.2.29 on 2026-05-14 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Driver', '0011_alter_driverprofile_current_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='driver_image',
            field=models.ImageField(blank=True, null=True, upload_to='drivers/profilepicture/'),
        ),
    ]
