# Generated by Django 4.2.29 on 2026-03-17 12:00

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Customer', '0001_initial'),
        ('Driver', '0004_drivervehicle_ride_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsRideRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_point', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('drop_point', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('pickup_address', models.TextField()),
                ('drop_address', models.TextField()),
                ('goods_type', models.CharField(choices=[('household', 'Household Items'), ('commercial', 'Commercial Goods'), ('fragile', 'Fragile Items'), ('electronics', 'Electronics'), ('furniture', 'Furniture'), ('other', 'Other')], default='household', max_length=20)),
                ('estimated_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('goods_description', models.TextField(blank=True, null=True)),
                ('vehicle_size_required', models.CharField(choices=[('mini_truck', 'Mini Truck'), ('tempo', 'Tempo'), ('lorry', 'Lorry')], default='mini_truck', max_length=20)),
                ('estimated_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('searching', 'Searching for Driver'), ('assigned', 'Driver Assigned'), ('started', 'Trip Started'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='searching', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_requests', to='Customer.customerprofile')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_assignments', to='Driver.driverprofile')),
                ('driver_vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_trips', to='Driver.drivervehicle')),
            ],
            options={
                'verbose_name': 'Goods Ride Request',
                'verbose_name_plural': 'Goods Ride Requests',
                'ordering': ['-requested_at'],
            },
        ),
    ]
