# Generated by Django 4.2.29 on 2026-03-16 06:08

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('home_location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, help_text="Customer's home address location", null=True, srid=4326)),
                ('driving_license_number', models.CharField(blank=True, max_length=50, null=True)),
                ('driving_license_expiry', models.DateField(blank=True, null=True)),
                ('driving_license_image', models.ImageField(blank=True, null=True, upload_to='customers/licenses/')),
                ('is_license_verified', models.BooleanField(default=False)),
                ('aadhar_number', models.CharField(blank=True, max_length=12, null=True)),
                ('aadhar_image', models.ImageField(blank=True, null=True, upload_to='customers/aadhar/')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('preferred_payment_method', models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('card', 'Card'), ('wallet', 'Wallet')], default='cash', max_length=20)),
                ('total_rides', models.IntegerField(default=0)),
                ('cancelled_rides', models.IntegerField(default=0)),
                ('ride_rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
                ('total_ride_spent', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_rentals', models.IntegerField(default=0)),
                ('active_rentals', models.IntegerField(default=0)),
                ('total_rental_spent', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_blocked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer Profile',
                'verbose_name_plural': 'Customer Profiles',
            },
        ),
    ]
