# Generated by Django 4.2.29 on 2026-03-27 12:40

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Driver', '0004_drivervehicle_ride_type_and_more'),
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('start_lon', models.DecimalField(decimal_places=6, max_digits=9)),
                ('end_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('end_lon', models.DecimalField(decimal_places=6, max_digits=9)),
                ('start_address', models.CharField(blank=True, max_length=255)),
                ('end_address', models.CharField(blank=True, max_length=255)),
                ('start_point', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('end_point', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('vehicle_type', models.CharField(choices=[('bike', 'Bike'), ('scooty', 'Scooty'), ('car_mini', 'Car – Mini (Alto, Wagon R)'), ('car_sedan', 'Car – Sedan (Dzire, Etios)'), ('car_suv', 'Car – SUV (Innova, Ertiga)'), ('car_premium', 'Car – Premium (Fortuner, XUV)')], default='car_mini', max_length=20)),
                ('ride_mode', models.CharField(choices=[('normal', 'Normal (Private)'), ('shared', 'Shared')], default='normal', max_length=10)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('base_fare', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('ride_price', models.DecimalField(blank=True, decimal_places=2, help_text='Driver earnings portion', max_digits=10, null=True)),
                ('tax_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Platform tax for website owner', max_digits=10, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, help_text='Total amount paid by customer', max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('driver_assigned', 'Driver Assigned'), ('started', 'Ride Started'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rides', to='Customer.customerprofile')),
                ('driver_vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rides', to='Driver.drivervehicle')),
            ],
            options={
                'verbose_name': 'Ride',
                'verbose_name_plural': 'Rides',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VehiclePricingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('bike', 'Bike'), ('scooty', 'Scooty'), ('car_mini', 'Car – Mini (Alto, Wagon R)'), ('car_sedan', 'Car – Sedan (Dzire, Etios)'), ('car_suv', 'Car – SUV (Innova, Ertiga)'), ('car_premium', 'Car – Premium (Fortuner, XUV)')], max_length=20)),
                ('ride_mode', models.CharField(choices=[('normal', 'Normal (Private)'), ('shared', 'Shared')], max_length=10)),
                ('base_fare', models.DecimalField(decimal_places=2, default=20.0, help_text='Flat base fare in ₹ charged at trip start', max_digits=8)),
                ('rate_per_km', models.DecimalField(decimal_places=2, help_text='Driver earning per km in ₹', max_digits=6)),
                ('tax_per_km', models.DecimalField(decimal_places=2, default=1.0, help_text='Platform tax per km in ₹ (goes to website owner)', max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vehicle Pricing Config',
                'verbose_name_plural': 'Vehicle Pricing Configs',
                'ordering': ['vehicle_type', 'ride_mode'],
                'unique_together': {('vehicle_type', 'ride_mode')},
            },
        ),
        migrations.CreateModel(
            name='RideTaxRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tax_per_km', models.DecimalField(decimal_places=2, max_digits=6)),
                ('settled', models.BooleanField(default=False, help_text='Has this tax been settled/paid out?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ride', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tax_record', to='Rides.ride')),
            ],
            options={
                'verbose_name': 'Ride Tax Record',
                'verbose_name_plural': 'Ride Tax Records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['status', 'created_at'], name='Rides_ride_status_9f3066_idx'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['vehicle_type', 'ride_mode'], name='Rides_ride_vehicle_fd245d_idx'),
        ),
    ]
