# Generated by Django 4.2.29 on 2026-03-27 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rides', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='vehicle_type',
            field=models.CharField(choices=[('bike', 'Bike'), ('auto', 'Auto'), ('scooty', 'Scooty'), ('car_mini', 'Car – Mini (Alto, Wagon R)'), ('car_sedan', 'Car – Sedan (Dzire, Etios)'), ('car_suv', 'Car – SUV (Innova, Ertiga)'), ('car_premium', 'Car – Premium (Fortuner, XUV)')], default='car_mini', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehiclepricingconfig',
            name='vehicle_type',
            field=models.CharField(choices=[('bike', 'Bike'), ('auto', 'Auto'), ('scooty', 'Scooty'), ('car_mini', 'Car – Mini (Alto, Wagon R)'), ('car_sedan', 'Car – Sedan (Dzire, Etios)'), ('car_suv', 'Car – SUV (Innova, Ertiga)'), ('car_premium', 'Car – Premium (Fortuner, XUV)')], max_length=20),
        ),
    ]
