# Generated by Django 4.2.29 on 2026-04-15 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rides', '0002_alter_ride_vehicle_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='vehicle_type',
            field=models.CharField(choices=[('bike', 'Bike'), ('auto', 'Auto'), ('scooty', 'Scooty'), ('car_mini', 'Car – Mini '), ('car_sedan', 'Car – Sedan '), ('car_suv', 'Car – SUV '), ('car_prem', 'Car – Prem ')], default='car_mini', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehiclepricingconfig',
            name='vehicle_type',
            field=models.CharField(choices=[('bike', 'Bike'), ('auto', 'Auto'), ('scooty', 'Scooty'), ('car_mini', 'Car – Mini '), ('car_sedan', 'Car – Sedan '), ('car_suv', 'Car – SUV '), ('car_prem', 'Car – Prem ')], max_length=20),
        ),
    ]
