# Generated by Django 4.2.29 on 2026-04-20 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Driver', '0004_drivervehicle_ride_type_and_more'),
        ('Rides', '0003_alter_ride_vehicle_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Driver.driverprofile'),
        ),
        migrations.AddField(
            model_name='ride',
            name='driver_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.CharField(choices=[('pending_driver_confirmation', 'Pending Driver Confirmation'), ('driver_assigned', 'Driver Assigned'), ('driver_arrived', 'Driver Arrived'), ('started', 'Ride Started'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending_driver_confirmation', max_length=30),
        ),
        migrations.AlterField(
            model_name='ride',
            name='vehicle_type',
            field=models.CharField(choices=[('bike', 'Bike'), ('auto', 'Auto'), ('scooty', 'Scooty'), ('car_mini', 'Car – Mini '), ('car_sedan', 'Car – Sedan '), ('car_suv', 'Car – SUV '), ('car_premium', 'Car - Premium ')], default='car_mini', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehiclepricingconfig',
            name='vehicle_type',
            field=models.CharField(choices=[('bike', 'Bike'), ('auto', 'Auto'), ('scooty', 'Scooty'), ('car_mini', 'Car – Mini '), ('car_sedan', 'Car – Sedan '), ('car_suv', 'Car – SUV '), ('car_premium', 'Car - Premium ')], max_length=20),
        ),
    ]
