# Generated by Django 4.2.29 on 2026-04-20 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Rides', '0004_ride_driver_ride_driver_accepted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rides', to=settings.AUTH_USER_MODEL),
        ),
    ]
