# Generated by Django 4.2.29 on 2026-05-12 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0002_alter_customerprofile_home_location_and_more'),
        ('Driver', '0011_alter_driverprofile_current_location_and_more'),
        ('Rides', '0005_alter_ride_customer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ride',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='ride',
            name='Rides_ride_status_9f3066_idx',
        ),
        migrations.RemoveIndex(
            model_name='ride',
            name='Rides_ride_vehicle_fd245d_idx',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='end_point',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='start_point',
        ),
        migrations.AddField(
            model_name='ride',
            name='booking_for',
            field=models.CharField(choices=[('self', 'Self'), ('friend', 'Friend'), ('family', 'Family'), ('other', 'Other')], default='self', max_length=20),
        ),
        migrations.AddField(
            model_name='ride',
            name='passenger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rides', to='Customer.customerpassenger'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='base_fare',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ride',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rides', to='Customer.customerprofile'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='distance_km',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='ride',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_rides', to='Driver.driverprofile'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='driver_vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Driver.drivervehicle'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='end_address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ride',
            name='end_lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ride',
            name='end_lon',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ride',
            name='ride_mode',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='ride',
            name='ride_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ride',
            name='start_address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ride',
            name='start_lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ride',
            name='start_lon',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.CharField(choices=[('pending_driver_confirmation', 'Pending Driver Confirmation'), ('driver_assigned', 'Driver Assigned'), ('driver_arrived', 'Driver Arrived'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending_driver_confirmation', max_length=40),
        ),
        migrations.AlterField(
            model_name='ride',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ride',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ride',
            name='vehicle_type',
            field=models.CharField(max_length=30),
        ),
    ]
