# Generated by Django 4.2.29 on 2026-05-14 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rides', '0006_alter_ride_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='otp',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
