# Generated by Django 4.2.29 on 2026-03-17 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('driver', 'Driver'), ('vehicle_owner', 'Vehicle Owner'), ('admin', 'Admin')], default='customer', max_length=30),
        ),
    ]
